sudo: required

services:
  - docker

before_install:
  - docker pull cdsteinkuehler/jessie-quartus-15.1.2
  - docker run cdsteinkuehler/jessie-quartus-15.1.2 /bin/sh -c "pwd"
  - docker ps -a

script:
  - ls
